### ISSUE TITLE
Remove payload length prefix

### ISSUE THREAD

**Issue by lukechampine** [NebulousLabs/writeaheadlog#60]
Currently, each marshaled page prefixes the payload with its length. I propose that this is actually unnecessary, because the contents of the payload can be decoded without knowing their length.

After encoding a set of updates, we split the `[]byte` across a set of pages. All of pages except for the last one are "full," meaning their payload length is `MaxPayloadSize` (or `maxFirstPagePayloadSize` for the first page). As such, when decoding, we can assume that simply concatenating all of the pages will produce a marshaled set of updates with no "gaps" of empty bytes in the middle. If we drop the length prefix of the payload, nothing changes, except that we may wind up with some trailing zeros at the end of the concatenated payloads. But these trailing zeros do not impair our ability to correctly decode the set of updates, because all fields in the `Update` struct are length-prefixed!

Actually, there is one hitch here. I was assuming that, like Sia's encoding package, the marshaled `[]Update` would be prefixed with the number of updates. It seems that this is not the case. And if we added it, then we haven't saved much space; for single-page payloads, the overhead is still 8 bytes. However, I believe we can still make do without any length prefixes. We just have to specify that an `Update` is invalid if its name is `""`. That way, if we encounter an update whose `Name` length-prefix is 0, we know that we've run into the trailing zeros.

**Comment by ChrisSchinnerl** [comment]
We should definitely remove the prefixes from each page but maybe we could add a prefix to the marshaled `[]Update` and instead remove the `Name`. The name is only used to differentiate between types of updates and most applications won't have more than 256 different types of updates. It is probably more efficient for the caller to prefix the instructions with a byte indicating the type of the `Update` instead of writing 8 bytes of name prefix + some characters.

**Comment by DavidVorick** [comment]
Every update needs to specify its length, and then we need to know the length of the whole package, either by having the length of the full payload or by knowing the number of updates.

My gut says that it's better to have the transaction encode the length of the whole payload, and then go through each update one at a time. The general reason is that if you encode the number of updates instead, and then one update has an error where it tells you to load too many bytes, you may oob. But if you know the length of the full payload that's less room for a mistake.

Doesn't make a big difference to me either way, and definitely if we have either of those, we no longer need the length of the payload for each page.

Each page then really only needs a pointer to the next page, which means we should be able to dedicate a full 4088 of each tail page to the payload.

**Comment by ChrisSchinnerl** [comment]
Having the transaction encode the length of the whole payload still leaves us with 8 bytes overhead for single page transactions though.The worst thing that could happen during an error is, that we load the whole page instead of a partial page, but that is already the case for all pages except the last one.

**Comment by DavidVorick** [comment]
1 page is 1 page, there's no performance difference between writing 1 page and 2 pages, the bytes we are saving help out in edge cases where you end up with 4 pages instead of 5 due to more compact page marshalling.
